// AUTO-PORTED from legacy locales/translations.json + delete-account.html
export const deleteAccount = {
  en: {
    title: "Delete Account & Data",
    back: "Back to Home",
    contentHtml: "<p>At <strong>Drive Test</strong> (developed by <strong>Mohsin Sapra</strong>), we value your privacy and provide you with full control over your personal data. If you no longer wish to use our services, you can request the deletion of your account and all associated data.</p><h2>How to Request Account Deletion</h2><p>You can request to have your account and associated data deleted by following these steps:</p><h3>1. In-App Deletion (Recommended)</h3><p>You can initiate account deletion directly within the Drive Test app. This is the fastest way to process your request:</p><div class='step-images'><div class='step-image-wrapper'><a href='/assets/delete-account/profile-tab.png' class='lightbox'><img src='/assets/delete-account/profile-tab.png' alt='Step 1: Go to Profile'></a><span class='step-label' data-i18n='delete_step1_label'>Step 1: Navigate to the Profile tab</span></div><div class='step-image-wrapper'><a href='/assets/delete-account/edit-page.png' class='lightbox'><img src='/assets/delete-account/edit-page.png' alt='Step 2: Edit Profile'></a><span class='step-label' data-i18n='delete_step2_label'>Step 2: Tap on Edit Profile</span></div><div class='step-image-wrapper'><a href='/assets/delete-account/delet-account.png' class='lightbox'><img src='/assets/delete-account/delet-account.png' alt='Step 3: Delete Account'></a><span class='step-label' data-i18n='delete_step3_label'>Step 3: Select \"Delete Account\"</span></div></div><h3>2. Via Email</h3><p>Alternatively, you can send an email to <a href='mailto:support@drivetest.se'>support@drivetest.se</a> with the subject line \"Account Deletion Request\". Please include the email address associated with your account. We will process your request within 30 days.</p><h2>Types of Data Deleted</h2><p>When you request account deletion, the following types of data will be permanently removed from our systems:</p><ul><li><strong>Account Information:</strong> Your name, email address, and authentication credentials.</li><li><strong>Study Progress:</strong> All your completed tests, bookmarks, and learning history.</li><li><strong>Performance Analytics:</strong> Your personal charts, graphs, and activity logs.</li></ul><h2>Data Retention</h2><p>Once an account deletion request is received and verified, we will process it within <strong>30 days</strong>. Please note:</p><ul><li>Certain data may be retained if required for legal, regulatory, or financial compliance (e.g., transaction records for premium subscriptions).</li><li>Non-identifiable, aggregated, and anonymized data may be kept for analytical purposes to improve our services.</li></ul><p>If you have any questions regarding this process, please contact us at <a href='mailto:support@drivetest.se'>support@drivetest.se</a>.</p>",
  },
  sv: {
    title: "Radera konto och data",
    back: "Tillbaka till startsidan",
    contentHtml: "<p>På <strong>Drive Test</strong> (utvecklad av <strong>Mohsin Sapra</strong>) värdesätter vi din integritet och ger dig full kontroll över dina personuppgifter. Om du inte längre vill använda våra tjänster kan du begära att ditt konto och all tillhörande data raderas.</p><h2>Hur du begär kontoborttagning</h2><p>Du kan begära att ditt konto och tillhörande data raderas genom att följa dessa steg:</p><h3>1. Borttagning i appen (Rekommenderas)</h3><p>Du kan initiera kontoborttagning direkt i Drive Test-appen. Detta är det snabbaste sättet att behandla din begäran:</p><div class='step-images'><div class='step-image-wrapper'><a href='/assets/delete-account/profile-tab.png' class='lightbox'><img src='/assets/delete-account/profile-tab.png' alt='Steg 1: Gå till Profil'></a><span class='step-label'>Steg 1: Navigera till fliken Profil</span></div><div class='step-image-wrapper'><a href='/assets/delete-account/edit-page.png' class='lightbox'><img src='/assets/delete-account/edit-page.png' alt='Steg 2: Redigera profil'></a><span class='step-label'>Steg 2: Tryck på Redigera profil</span></div><div class='step-image-wrapper'><a href='/assets/delete-account/delet-account.png' class='lightbox'><img src='/assets/delete-account/delet-account.png' alt='Steg 3: Radera konto'></a><span class='step-label'>Steg 3: Välj \"Radera konto\"</span></div></div><h3>2. Via e-post</h3><p>Alternativt kan du skicka ett e-postmeddelande till <a href='mailto:support@drivetest.se'>support@drivetest.se</a> med ämnesraden \"Begäran om kontoborttagning\". Ange den e-postadress som är kopplad till ditt konto. Vi behandlar din begäran inom 30 dagar.</p><h2>Typer av data som raderas</h2><p>När du begär kontoborttagning kommer följande typer av data att permanent tas bort från våra system:</p><ul><li><strong>Kontoinformation:</strong> Ditt namn, din e-postadress och dina inloggningsuppgifter.</li><li><strong>Studieutveckling:</strong> Alla dina genomförda prov, bokmärken och inlärningshistorik.</li><li><strong>Prestandaanalys:</strong> Dina personliga diagram, grafer och aktivitetsloggar.</li></ul><h2>Datalagring</h2><p>När en begäran om kontoborttagning har mottagits och verifierats behandlar vi den inom <strong>30 dagar</strong>. Observera:</p><ul><li>Vissa uppgifter kan behållas om det krävs för juridisk, regulatorisk eller finansiell efterlevnad (t.ex. transaktionsregister för premiumprenumerationer).</li><li>Icke-identifierbar, aggregerad och anonymiserad data kan behållas för analytiska ändamål för att förbättra våra tjänster.</li></ul><p>Om du har frågor om denna process, kontakta oss på <a href='mailto:support@drivetest.se'>support@drivetest.se</a>.</p>",
  },
};
