// AUTO-PORTED from legacy locales/translations.json + index.html
export const home = {
  en: {
    "home_name": "Drive Test",
    "home_description": "Pass Taxi, Company & Transport Exams",
    "home_screenshots_title": "Screenshots",
    "home_description_title": "Description",
    "home_cta_title": "Need a Taxi License?",
    "home_cta_body": "Learn everything you need to know about getting your taxi driver's license in Sweden. Our comprehensive guide covers requirements, exams, costs, and the complete application process.",
    "home_cta_btn": "View License Guide →",
    "home_hero_eyebrow": "Sweden's taxi & transport exam prep",
    "home_hero_hint": "Scroll",
    "home_stat_questions_label": "Official-style questions",
    "home_stat_modes_label": "Study modes",
    "home_stat_platforms_label": "Platforms",
    "home_screens_sub": "A look inside the app",
    "home_features_kicker": "Features",
    "home_features_title": "Built to get you passed",
    "home_features_sub": "Everything you need to walk into the exam room confident.",
    "home_tools_kicker": "Free Tools",
    "home_tools_title": "Tools for taxi drivers",
    "home_tools_sub": "Free browser tools that make a driver's life easier — no install, nothing to sign up for.",
    "home_tool_ob_title": "OB Calculator",
    "home_tool_ob_desc": "Snap a photo of your Vilotidsrapport (rest-time slip) and get your OB1 / OB2 hours and pay instantly. AI reads the handwriting, you verify, and the maths is exact.",
    "home_tool_ob_btn": "Open OB Calculator →",
    "home_feature1_title": "Versatile Test Modes",
    "home_feature1_desc": "Practice, Custom and Review modes to suit your daily study goals.",
    "home_feature2_title": "Multi-Language & Text-to-Speech",
    "home_feature2_desc": "Don't let language barriers stop you — full text-to-speech support helps comprehension.",
    "home_feature3_title": "Deep Dive Explanations",
    "home_feature3_desc": "We don't just give you the answer — we explain why it's correct.",
    "home_feature4_title": "Smart Bookmarking",
    "home_feature4_desc": "Instantly save and revisit difficult questions to turn weaknesses into strengths.",
    "home_feature5_title": "Performance Analytics",
    "home_feature5_desc": "Visual charts and graphs break down your readiness in real-time.",
    "home_feature6_title": "Exam-Ready Content",
    "home_feature6_desc": "Specialized prep for Taxiförarlegitimation and Yrkeskunnande.",
    "home_desc_heading": "Everything about Drive Test",
    "home_desc_more": "Read full description",
    "home_desc_less": "Show less",
    "home_download_title": "Your licence starts here",
    "home_download_sub": "Download Drive Test free on Android, iOS or use it right in your browser.",
    "home_dock_label": "Get the app",
    "home_phone_try": "Try it live",
    "home_modal_close": "Close",
    "home_feature_ai_title": "Your Personal AI Tutor",
    "home_feature_ai_desc": "Stuck on a question? Your built-in AI tutor steps in with clear, personal explanations until it clicks.",
    "home_cta_kicker": "License Guide",
    "home_cta_chip1": "≈ 2 months process",
    "home_cta_chip2": "4 exams to pass",
    "home_cta_chip3": "Total cost 4 425 kr",
    "home_store_play_top": "Get it on",
    "home_store_ios_top": "Download on the",
    "home_store_web_top": "Launch as",
    "home_store_web_name": "Web App",
    descriptionHtml: "<p>DriveTest: Master Your Swedish Taxi License &amp; Driving Exams</p><p>Secure your future on the road. DriveTest is the ultimate study companion for anyone looking to pass their taxi licence in Sweden or upgrade to a professional taxi company licence in Sweden.</p><p>Whether you are studying for your standard B-license, aiming for your professional Taxiförarlegitimation, or preparing for the rigorous certification required to run a taxi business, DriveTest provides the tools you need to succeed on the first try.</p><hr><p>Why Choose DriveTest?</p><p>Passing the Swedish Transport Administration (Trafikverket) exams requires focused preparation. Our app replaces outdated textbooks with intelligent, interactive learning. We combine comprehensive question banks with smart analytics to ensure you are fully prepared for both the Taxi Driver License and the Taxi Company License exams.</p><p>Stop guessing and start passing. With thousands of official-style questions, deep performance insights, and multi-language support, you'll know exactly where you stand before you enter the exam room.</p><hr><p>🚀 Powerful Study Features</p><p>Tailor your learning experience to fit your schedule and learning style.</p><ul><li>Versatile Test Modes: Choose from Practice, Custom, or Review modes to suit your daily study goals</li><li>Multi-Language Support: Don't let language barriers stop you. Includes full text-to-speech support to help with comprehension</li><li>Deep Dive Explanations: We don't just give you the answer; we explain why it is correct, crucial for the complex theory behind the taxi company licence in Sweden</li><li>Smart Bookmarking: Instantly save and revisit difficult questions to turn your weaknesses into strengths</li></ul><hr><p>📈 Visual Progress Tracking</p><p>Track your growth from novice to pro with our advanced analytics dashboard.</p><ul><li>Performance Analytics: Visual charts and graphs break down your readiness in real-time</li><li>Category Breakdowns: See exactly which areas of the taxi licence Sweden theory you have mastered and where you need more focus</li><li>Comprehensive History: Access your complete test history with detailed reviews</li><li>Activity Logs: Keep yourself accountable with daily and weekly activity tracking</li></ul><hr><p>💎 Premium Access &amp; Content</p><p>Unlock the full potential of DriveTest with our flexible premium plans.</p><ul><li>Affordable Subscriptions: Category-based access for just 100 SEK/month</li><li>Expert Video Content: Educational videos designed to clarify complex traffic rules and regulations</li><li>Secure Payments: Seamless transactions via Card, Apple Pay, and Google Pay</li><li>Free Trial Areas: Explore free categories before you commit</li></ul><hr><p>Key Features at a Glance</p><p>✓ Specialized prep for Taxi Licence Sweden (Taxiförarlegitimation)<br>✓ Study material for Taxi Company Licence in Sweden (Yrkeskunnande)<br>✓ Practice, Custom, and Review modes<br>✓ Multi-language text-to-speech support<br>✓ Detailed answer explanations for deep learning<br>✓ Customizable test settings (length, timer, marking criteria)<br>✓ Offline access to your test history<br>✓ Screenshot protection for exam integrity<br>✓ Secure payment processing (Stripe, Apple Pay, Google Pay)</p><hr><p>Download DriveTest today and start your journey to becoming a licensed taxi professional in Sweden.</p>",
    marquee: ["Taxiförarlegitimation", "AI Tutor", "Yrkeskunnande", "B-körkort", "Map Reading", "Traffic & Safety", "Professional Knowledge"],
  },
  sv: {
    "home_name": "Drive Test",
    "home_description": "Klara Taxi-, Företags- & Transportprov",
    "home_screenshots_title": "Skärmdumpar",
    "home_description_title": "Beskrivning",
    "home_cta_title": "Behöver du taxiförarlegitimation?",
    "home_cta_body": "Lär dig allt du behöver veta om att skaffa din taxiförarlegitimation i Sverige. Vår kompletta guide täcker krav, prov, kostnader och hela ansökningsprocessen.",
    "home_cta_btn": "Se licensguiden →",
    "home_hero_eyebrow": "Provträning för taxi & transport i Sverige",
    "home_hero_hint": "Scrolla",
    "home_stat_questions_label": "Frågor i officiell stil",
    "home_stat_modes_label": "Studielägen",
    "home_stat_platforms_label": "Plattformar",
    "home_screens_sub": "En titt inuti appen",
    "home_features_kicker": "Funktioner",
    "home_features_title": "Byggd för att du ska klara provet",
    "home_features_sub": "Allt du behöver för att kliva in i provsalen med självförtroende.",
    "home_tools_kicker": "Gratis verktyg",
    "home_tools_title": "Verktyg för taxiförare",
    "home_tools_sub": "Gratis webbverktyg som gör förarlivet enklare — ingen installation, ingen registrering.",
    "home_tool_ob_title": "OB-kalkylator",
    "home_tool_ob_desc": "Fota din vilotidsrapport och få direkt dina OB1/OB2-timmar och lön. AI läser handstilen, du verifierar, och beräkningen är exakt.",
    "home_tool_ob_btn": "Öppna OB-kalkylator →",
    "home_feature1_title": "Mångsidiga testlägen",
    "home_feature1_desc": "Övning, Anpassat och Granska-läge för dina dagliga studiemål.",
    "home_feature2_title": "Flerspråkigt stöd & text-till-tal",
    "home_feature2_desc": "Låt inte språkbarriärer stoppa dig — fullt text-till-tal-stöd för bättre förståelse.",
    "home_feature3_title": "Djupgående förklaringar",
    "home_feature3_desc": "Vi ger dig inte bara svaret — vi förklarar varför det är rätt.",
    "home_feature4_title": "Smart bokmärkning",
    "home_feature4_desc": "Spara och återbesök svåra frågor direkt för att omvandla svagheter till styrkor.",
    "home_feature5_title": "Prestandaanalys",
    "home_feature5_desc": "Visuella diagram och grafer visar din beredskap i realtid.",
    "home_feature6_title": "Provfärdigt innehåll",
    "home_feature6_desc": "Specialiserad förberedelse för Taxiförarlegitimation och Yrkeskunnande.",
    "home_desc_heading": "Allt om Drive Test",
    "home_desc_more": "Läs hela beskrivningen",
    "home_desc_less": "Visa mindre",
    "home_download_title": "Din legitimation börjar här",
    "home_download_sub": "Ladda ned Drive Test gratis till Android och iOS, eller använd den direkt i webbläsaren.",
    "home_dock_label": "Skaffa appen",
    "home_phone_try": "Testa direkt",
    "home_modal_close": "Stäng",
    "home_feature_ai_title": "Din personliga AI-tutor",
    "home_feature_ai_desc": "Fastnat på en fråga? Din inbyggda AI-tutor förklarar tydligt och personligt tills det sitter.",
    "home_cta_kicker": "Licensguide",
    "home_cta_chip1": "≈ 2 månaders process",
    "home_cta_chip2": "4 prov att klara",
    "home_cta_chip3": "Total kostnad 4 425 kr",
    "home_store_play_top": "Ladda ned på",
    "home_store_ios_top": "Hämta i",
    "home_store_web_top": "Öppna som",
    "home_store_web_name": "Webbapp",
    descriptionHtml: "<p>DriveTest: Bemästra din svenska taxilegitimation och körkortsexamen</p><p>Säkra din framtid på vägen. DriveTest är den ultimata studiekompisen för alla som vill klara taxiförarlegitimationen i Sverige eller uppgradera till en professionell taxiföretagslicens.</p><p>Oavsett om du studerar för ditt vanliga B-körkort, siktar på din professionella Taxiförarlegitimation, eller förbereder dig för den krävande certifieringen som krävs för att driva ett taxiföretag — ger DriveTest dig de verktyg du behöver för att lyckas på första försöket.</p><hr><p>Varför välja DriveTest?</p><p>Att klara Trafikverkets prov kräver fokuserad förberedelse. Vår app ersätter föråldrade läroböcker med intelligent, interaktivt lärande. Vi kombinerar omfattande frågebanker med smarta analyser för att säkerställa att du är fullt förberedd inför både Taxiförarlegitimationens och Yrkeskunnandeprovet.</p><p>Sluta gissa och börja klara proven. Med tusentals frågor i officiell stil, djupa prestandainsikter och flerspråkigt stöd vet du exakt var du befinner dig innan du kliver in i provsalen.</p><hr><p>🚀 Kraftfulla studiefunktioner</p><p>Anpassa din inlärningsupplevelse efter ditt schema och din inlärningsstil.</p><ul><li>Mångsidiga testlägen: Välj mellan Övning, Anpassat eller Granska-läge för dina dagliga studiemål</li><li>Flerspråkigt stöd: Låt inte språkbarriärer stoppa dig. Inkluderar fullt text-till-tal-stöd för bättre förståelse</li><li>Djupgående förklaringar: Vi ger dig inte bara svaret — vi förklarar varför det är rätt, avgörande för den komplexa teorin bakom taxiföretagslicensen</li><li>Smart bokmärkning: Spara och återbesök svåra frågor direkt för att omvandla svagheter till styrkor</li></ul><hr><p>📈 Visuell framstegsspårning</p><p>Följ din utveckling från nybörjare till proffs med vår avancerade analysdashboard.</p><ul><li>Prestandaanalys: Visuella diagram och grafer visar din beredskap i realtid</li><li>Kategoriuppdelning: Se exakt vilka områden av taxilicensteorin du behärskar och var du behöver mer fokus</li><li>Fullständig historik: Tillgång till hela din testhistorik med detaljerade genomgångar</li><li>Aktivitetsloggar: Håll dig ansvarig med daglig och veckovis aktivitetsspårning</li></ul><hr><p>💎 Premium-åtkomst och innehåll</p><p>Lås upp DriveTests fulla potential med våra flexibla premiumplaner.</p><ul><li>Prisvärda prenumerationer: Kategoribaserad åtkomst för bara 100 kr/månad</li><li>Expertvideoinnehåll: Utbildningsvideor utformade för att klargöra komplexa trafikregler och föreskrifter</li><li>Säkra betalningar: Sömlösa transaktioner via kort, Apple Pay och Google Pay</li><li>Gratis provområden: Utforska gratis kategorier innan du bestämmer dig</li></ul><hr><p>Nyckelfunktioner i korthet</p><p>✓ Specialiserad förberedelse för Taxiförarlegitimation<br>✓ Studiematerial för Yrkeskunnande (taxiföretagslicens)<br>✓ Övning-, Anpassat- och Granska-lägen<br>✓ Flerspråkigt text-till-tal-stöd<br>✓ Detaljerade svarförklaringar för djupinlärning<br>✓ Anpassningsbara testinställningar (längd, timer, bedömningskriterier)<br>✓ Offlineåtkomst till din testhistorik<br>✓ Skärmdumpsskydd för provintegritet<br>✓ Säker betalningshantering (Stripe, Apple Pay, Google Pay)</p><hr><p>Ladda ned DriveTest idag och börja din resa mot att bli en licensierad taxiproffs i Sverige.</p>",
    marquee: ["Taxiförarlegitimation", "AI Tutor", "Yrkeskunnande", "B-körkort", "Kartläsning", "Trafik & säkerhet", "Yrkeskunnande"],
  },
};

// Pricing derived from the real facts stated in home_description_html.
export const pricing = {
  en: {
    kicker: "Pricing",
    title: "Simple, category-based pricing",
    sub: "Purchases are made securely inside the app via the App Store, Google Play or Stripe.",
    plans: [
      {
        name: "Free",
        price: "0 kr",
        period: "",
        features: [
          "Free trial categories to explore before you commit",
          "Practice, Custom and Review modes",
          "Bookmarking and basic progress tracking",
        ],
      },
      {
        name: "Premium",
        price: "100 SEK",
        period: "/ month per category",
        features: [
          "Full category-based access (e.g. Taxiförarlegitimation, Yrkeskunnande, B-körkort)",
          "Expert video content explaining complex traffic rules",
          "Secure payments via Card, Apple Pay and Google Pay",
          "Deep-dive explanations and performance analytics",
        ],
      },
    ],
    note: "Prices and included categories may vary — always confirm in-app before purchase.",
  },
  sv: {
    kicker: "Priser",
    title: "Enkel prissättning per kategori",
    sub: "Köp görs säkert i appen via App Store, Google Play eller Stripe.",
    plans: [
      {
        name: "Gratis",
        price: "0 kr",
        period: "",
        features: [
          "Gratis provkategorier att utforska innan du bestämmer dig",
          "Övning-, Anpassat- och Granska-läge",
          "Bokmärkning och grundläggande framstegsspårning",
        ],
      },
      {
        name: "Premium",
        price: "100 kr",
        period: "/ månad per kategori",
        features: [
          "Full kategoribaserad åtkomst (t.ex. Taxiförarlegitimation, Yrkeskunnande, B-körkort)",
          "Expertvideoinnehåll som förklarar komplexa trafikregler",
          "Säkra betalningar via kort, Apple Pay och Google Pay",
          "Djupgående förklaringar och prestandaanalys",
        ],
      },
    ],
    note: "Priser och ingående kategorier kan variera — bekräfta alltid i appen innan köp.",
  },
};

export const howItWorks = {
  en: {
    title: "How it works",
    subtitle: "From first question to licence — in three simple steps.",
    steps: [
      {
        tag: "STEP 1",
        title: "Choose your exam",
        desc: "Pick the licence track that matches your goal — Taxiförarlegitimation, Yrkeskunnande, or the Medborgarskapsprov — and we load the right question bank instantly.",
      },
      {
        tag: "STEP 2",
        title: "Practice with your AI tutor",
        desc: "Answer realistic, official-style questions. The moment something doesn't click, your AI tutor steps in and explains the reasoning until it does.",
      },
      {
        tag: "STEP 3",
        title: "Track your progress & pass",
        desc: "Watch your readiness score climb with every session, spot weak categories at a glance, and walk into the exam room knowing you're ready.",
      },
    ],
  },
  sv: {
    title: "Så fungerar det",
    subtitle: "Från första frågan till legitimation — i tre enkla steg.",
    steps: [
      {
        tag: "STEG 1",
        title: "Välj ditt prov",
        desc: "Välj den licensinriktning som matchar ditt mål — Taxiförarlegitimation, Yrkeskunnande eller Medborgarskapsprovet — så laddar vi rätt frågebank direkt.",
      },
      {
        tag: "STEG 2",
        title: "Öva med din AI-tutor",
        desc: "Svara på realistiska frågor i officiell stil. Så fort något känns oklart förklarar din AI-tutor resonemanget tills det sitter.",
      },
      {
        tag: "STEG 3",
        title: "Följ dina framsteg & klara provet",
        desc: "Se din beredskap växa för varje övningspass, upptäck svaga kategorier direkt och kliv in i provsalen med vetskapen att du är redo.",
      },
    ],
  },
};

// Example question for the interactive QuizDemo (Step 2 mockup) — illustrative only, not official exam content.
export const demo = {
  en: {
    collageLabel1: "Taxiförarlegitimation",
    collagePills1: ["Map Reading", "Traffic & Safety", "Professional Knowledge"],
    collageLabel2: "Yrkeskunnande",
    collageSub2: "Taxi company licence",
    collageLabel3: "Medborgarskapsprov",
    collageSub3: "136 questions · 13 chapters",
    question: "You're approaching a zebra crossing where a pedestrian is waiting to cross. What should you do?",
    options: [
      "Slow down and be prepared to stop",
      "Speed up to pass before they step out",
      "Sound the horn to warn them",
      "Ignore them since they haven't stepped onto the road",
    ],
    correctIndex: 0,
    explanationTitle: "Deep dive explanation",
    explanation:
      "Swedish law requires you to give way to pedestrians at a zebra crossing (övergångsställe) as soon as they show intent to cross. Slowing down and preparing to stop keeps everyone safe and is the correct, exam-tested answer.",
    askAiBtn: "Ask AI tutor ✦",
    aiBubbleText:
      "Think of it this way: a raised hand or a step toward the curb both count as \"showing intent\". Trafikverket expects you to yield the instant that happens — not wait until they're already in the lane.",
    ttsLabel: "Text-to-speech",
    tryAgainLabel: "Try again",
    scoreLabel: "Score",
    progressLabel: "Question 1 of 1",
    correctLabel: "Correct!",
    wrongLabel: "Not quite",
    readinessLabel: "Readiness",
    bookmarksLabel: "Bookmarks",
    streakLabel: "Day streak",
    categoryLabels: ["Map Reading", "Traffic & Safety", "Professional Knowledge", "Regulations"],
  },
  sv: {
    collageLabel1: "Taxiförarlegitimation",
    collagePills1: ["Kartläsning", "Trafik & säkerhet", "Yrkeskunskap"],
    collageLabel2: "Yrkeskunnande",
    collageSub2: "Taxiföretagslicens",
    collageLabel3: "Medborgarskapsprov",
    collageSub3: "136 frågor · 13 kapitel",
    question: "Du närmar dig ett övergångsställe där en fotgängare väntar på att gå över. Vad ska du göra?",
    options: [
      "Sakta ner och var beredd att stanna",
      "Öka farten för att hinna förbi innan de går ut",
      "Tuta för att varna dem",
      "Strunta i dem eftersom de inte gått ut på vägen än",
    ],
    correctIndex: 0,
    explanationTitle: "Djupgående förklaring",
    explanation:
      "Enligt svensk lag måste du lämna företräde åt fotgängare vid ett övergångsställe så snart de visar avsikt att gå över. Att sakta ner och vara beredd att stanna håller alla säkra och är det korrekta, provtestade svaret.",
    askAiBtn: "Fråga AI-tutor ✦",
    aiBubbleText:
      "Tänk så här: en höjd hand eller ett steg mot trottoarkanten räknas båda som att \"visa avsikt\". Trafikverket förväntar sig att du lämnar företräde direkt då — inte väntar tills de redan är ute i körfältet.",
    ttsLabel: "Text-till-tal",
    tryAgainLabel: "Försök igen",
    scoreLabel: "Poäng",
    progressLabel: "Fråga 1 av 1",
    correctLabel: "Rätt svar!",
    wrongLabel: "Inte riktigt",
    readinessLabel: "Beredskap",
    bookmarksLabel: "Bokmärken",
    streakLabel: "Dagars streak",
    categoryLabels: ["Kartläsning", "Trafik & säkerhet", "Yrkeskunskap", "Regler"],
  },
};

export const faq = {
  en: [
    { q: "Can I use my account on multiple devices?", a: "Yes. Sign in with the same Google or Apple account on any device and your progress, subscriptions, and settings will sync automatically." },
    { q: "I can't log in — what should I do?", a: "Make sure you're using the same sign-in method (Google or Apple) you used when you first registered. If the problem persists, try signing out of your Google/Apple account on the device and signing back in, then retry. If you're still stuck, <a href=\"mailto:support@drivetest.se\">email us</a> with your registered email address." },
    { q: "How do I delete my account and data?", a: "You can request full account and data deletion from the app under <strong>Settings → Delete Account</strong>, or visit our <a href=\"delete-account.html\">Delete Account page</a> for step-by-step instructions." },
    { q: "How do I cancel my subscription?", a: "Subscriptions are managed through the App Store (iOS) or Google Play (Android). On iPhone: go to <strong>Settings → [your name] → Subscriptions</strong>, select Drive Test, and tap <em>Cancel Subscription</em>. On Android: open Google Play → tap your profile → <em>Payments &amp; subscriptions → Subscriptions</em>." },
    { q: "I was charged but can't access premium content.", a: "Go to <strong>Settings → Restore Purchases</strong> inside the app. This re-validates your active subscription with the App Store or Google Play. If the issue continues after restoring, <a href=\"mailto:support@drivetest.se\">contact us</a> and include your order number or a screenshot of your receipt." },
    { q: "Can I get a refund?", a: "Refunds are handled by Apple or Google depending on where you purchased. For App Store purchases, visit <a href=\"https://reportaproblem.apple.com\" target=\"_blank\" rel=\"noopener\">reportaproblem.apple.com</a>. For Google Play, open the Play Store → order history → tap the order → <em>Request a refund</em>. We're happy to assist if you have trouble." },
    { q: "I found an incorrect question or answer.", a: "We take accuracy seriously. Please email us at <a href=\"mailto:support@drivetest.se\">support@drivetest.se</a> with the question text and the category you found it in. We review all reports and update content regularly." },
    { q: "My progress was reset — can I recover it?", a: "Progress is tied to your account and syncs to our servers when you're online. If you recently reinstalled the app, open it and sign in again — your progress should restore automatically within a few seconds. If data is still missing, contact us with your account email and the approximate date of the reset." },
    { q: "The app crashes or won't open.", a: "Try these steps in order: (1) Force-close the app and reopen it. (2) Restart your device. (3) Make sure you're running the latest version of Drive Test from the App Store or Google Play. (4) If none of those work, reinstall the app — your data is saved to your account and will be restored on sign-in. Still stuck? <a href=\"mailto:support@drivetest.se\">Let us know</a>." },
    { q: "I'm not receiving notifications.", a: "Check that notifications are enabled: on iPhone go to <strong>Settings → Drive Test → Notifications</strong> and ensure they're turned on. Inside the app, check <strong>Settings → Notifications</strong> to make sure your study reminders are active. If you've recently reinstalled the app, you may need to grant notification permission again." },
  ],
  sv: [
    { q: "Kan jag använda mitt konto på flera enheter?", a: "Ja. Logga in med samma Google- eller Apple-konto på vilken enhet som helst och dina framsteg, prenumerationer och inställningar synkroniseras automatiskt." },
    { q: "Jag kan inte logga in — vad ska jag göra?", a: "Kontrollera att du använder samma inloggningsmetod (Google eller Apple) som du använde vid registreringen. Om problemet kvarstår, prova att logga ut från ditt Google/Apple-konto på enheten och logga in igen. Fortfarande problem? <a href=\"mailto:support@drivetest.se\">Maila oss</a> med din registrerade e-postadress." },
    { q: "Hur raderar jag mitt konto och mina uppgifter?", a: "Du kan begära fullständig radering av konto och data i appen under <strong>Inställningar → Radera konto</strong>, eller besök vår <a href=\"delete-account.html\">sida för kontoborttagning</a> för steg-för-steg-instruktioner." },
    { q: "Hur avslutar jag min prenumeration?", a: "Prenumerationer hanteras via App Store (iOS) eller Google Play (Android). På iPhone: gå till <strong>Inställningar → [ditt namn] → Prenumerationer</strong>, välj Drive Test och tryck på <em>Avsluta prenumeration</em>. På Android: öppna Google Play → tryck på din profil → <em>Betalningar och prenumerationer → Prenumerationer</em>." },
    { q: "Jag har blivit debiterad men kan inte komma åt premiuminnehåll.", a: "Gå till <strong>Inställningar → Återställ köp</strong> i appen. Detta validerar om din aktiva prenumeration med App Store eller Google Play. Om problemet kvarstår, <a href=\"mailto:support@drivetest.se\">kontakta oss</a> och inkludera ditt ordernummer eller en skärmdump på kvittot." },
    { q: "Kan jag få en återbetalning?", a: "Återbetalningar hanteras av Apple eller Google. För App Store-köp, besök <a href=\"https://reportaproblem.apple.com\" target=\"_blank\" rel=\"noopener\">reportaproblem.apple.com</a>. För Google Play: öppna Play Store → orderhistorik → tryck på ordern → <em>Begär återbetalning</em>. Vi hjälper gärna till om du har problem." },
    { q: "Jag hittade en felaktig fråga eller ett felaktigt svar.", a: "Vi tar noggrannhet på allvar. Maila oss på <a href=\"mailto:support@drivetest.se\">support@drivetest.se</a> med frågetexten och kategorin där du hittade det. Vi granskar alla rapporter och uppdaterar innehållet regelbundet." },
    { q: "Mitt framsteg har återställts — kan jag återfå det?", a: "Framsteg är knutet till ditt konto och synkroniseras med våra servrar när du är online. Om du nyligen installerat om appen, logga in igen — dina framsteg bör återställas automatiskt inom några sekunder. Saknas data fortfarande? Kontakta oss med din e-post och det ungefärliga datumet för återställningen." },
    { q: "Appen kraschar eller öppnas inte.", a: "Prova dessa steg i ordning: (1) Tvångsstäng appen och öppna den igen. (2) Starta om din enhet. (3) Kontrollera att du kör den senaste versionen från App Store eller Google Play. (4) Installera om appen — dina data är sparade på ditt konto och återställs vid inloggning. Fortfarande problem? <a href=\"mailto:support@drivetest.se\">Hör av dig</a>." },
    { q: "Jag får inga notiser.", a: "Kontrollera att notiser är aktiverade: på iPhone, gå till <strong>Inställningar → Drive Test → Notiser</strong> och se till att de är påslagna. I appen, kontrollera <strong>Inställningar → Notiser</strong> för att säkerställa att dina studiepåminnelser är aktiva. Om du nyligen installerat om appen kan du behöva bevilja notisbehörighet igen." },
  ],
};
