// AUTO-PORTED from legacy locales/translations.json + support.html
export const support = {
  en: {
    "support_badge": "Help Center",
    "support_hero_title": "How can we help you?",
    "support_hero_subtitle": "Find answers to common questions or get in touch with our support team.",
    "support_topic_account_title": "Account & Login",
    "support_topic_account_desc": "Sign-in, password, profile settings",
    "support_topic_billing_title": "Billing & Subscription",
    "support_topic_billing_desc": "Plans, payments, refunds, cancellation",
    "support_topic_content_title": "Exam Content",
    "support_topic_content_desc": "Questions, categories, progress",
    "support_topic_technical_title": "Technical Issues",
    "support_topic_technical_desc": "App crashes, sync, notifications",
    "support_faq_title": "Frequently Asked Questions",
    "support_q1": "Can I use my account on multiple devices?",
    "support_a1": "Yes. Sign in with the same Google or Apple account on any device and your progress, subscriptions, and settings will sync automatically.",
    "support_q2": "I can't log in — what should I do?",
    "support_a2": "Make sure you're using the same sign-in method (Google or Apple) you used when you first registered. If the problem persists, try signing out of your Google/Apple account on the device and signing back in, then retry. If you're still stuck, <a href=\"mailto:support@drivetest.se\">email us</a> with your registered email address.",
    "support_q3": "How do I delete my account and data?",
    "support_a3": "You can request full account and data deletion from the app under <strong>Settings → Delete Account</strong>, or visit our <a href=\"delete-account.html\">Delete Account page</a> for step-by-step instructions.",
    "support_q4": "How do I cancel my subscription?",
    "support_q4_a": "Subscriptions are managed through the App Store (iOS) or Google Play (Android). On iPhone: go to <strong>Settings → [your name] → Subscriptions</strong>, select Drive Test, and tap <em>Cancel Subscription</em>. On Android: open Google Play → tap your profile → <em>Payments &amp; subscriptions → Subscriptions</em>.",
    "support_q5": "I was charged but can't access premium content.",
    "support_a5": "Go to <strong>Settings → Restore Purchases</strong> inside the app. This re-validates your active subscription with the App Store or Google Play. If the issue continues after restoring, <a href=\"mailto:support@drivetest.se\">contact us</a> and include your order number or a screenshot of your receipt.",
    "support_q6": "Can I get a refund?",
    "support_a6": "Refunds are handled by Apple or Google depending on where you purchased. For App Store purchases, visit <a href=\"https://reportaproblem.apple.com\" target=\"_blank\" rel=\"noopener\">reportaproblem.apple.com</a>. For Google Play, open the Play Store → order history → tap the order → <em>Request a refund</em>. We're happy to assist if you have trouble.",
    "support_q7": "I found an incorrect question or answer.",
    "support_a7": "We take accuracy seriously. Please email us at <a href=\"mailto:support@drivetest.se\">support@drivetest.se</a> with the question text and the category you found it in. We review all reports and update content regularly.",
    "support_q8": "My progress was reset — can I recover it?",
    "support_a8": "Progress is tied to your account and syncs to our servers when you're online. If you recently reinstalled the app, open it and sign in again — your progress should restore automatically within a few seconds. If data is still missing, contact us with your account email and the approximate date of the reset.",
    "support_q9": "The app crashes or won't open.",
    "support_a9": "Try these steps in order: (1) Force-close the app and reopen it. (2) Restart your device. (3) Make sure you're running the latest version of Drive Test from the App Store or Google Play. (4) If none of those work, reinstall the app — your data is saved to your account and will be restored on sign-in. Still stuck? <a href=\"mailto:support@drivetest.se\">Let us know</a>.",
    "support_q10": "I'm not receiving notifications.",
    "support_a10": "Check that notifications are enabled: on iPhone go to <strong>Settings → Drive Test → Notifications</strong> and ensure they're turned on. Inside the app, check <strong>Settings → Notifications</strong> to make sure your study reminders are active. If you've recently reinstalled the app, you may need to grant notification permission again.",
    "support_contact_title": "How to reach us",
    "support_step1_title": "Check the FAQ above",
    "support_step1_desc": "Most questions are answered there — it's the fastest way to get help.",
    "support_step2_title": "Email us",
    "support_step2_desc": "Send a message to <strong>support@drivetest.se</strong> describing your issue. Include your device model, iOS/Android version, and app version if possible.",
    "support_step3_title": "We'll get back to you",
    "support_step3_desc": "We respond to all emails within 1–2 business days. Complex issues may take a little longer but we always follow up.",
    "support_cta_title": "Still need help?",
    "support_cta_desc": "Our support team is ready to help you with any question about Drive Test.",
    "support_cta_email_btn": "✉ Email Support",
    "support_cta_delete_btn": "Delete Account",
    "support_badge_reply": "⏱ Reply within 1–2 business days",
    "support_badge_lang": "🌍 English & Swedish",
    "page_title_support": "Support - Drive Test",
  },
  sv: {
    "support_badge": "Hjälpcenter",
    "support_hero_title": "Hur kan vi hjälpa dig?",
    "support_hero_subtitle": "Hitta svar på vanliga frågor eller kontakta vårt supportteam.",
    "support_topic_account_title": "Konto & Inloggning",
    "support_topic_account_desc": "Inloggning, lösenord, profilinställningar",
    "support_topic_billing_title": "Fakturering & Prenumeration",
    "support_topic_billing_desc": "Planer, betalningar, återbetalningar, avslut",
    "support_topic_content_title": "Provinnehåll",
    "support_topic_content_desc": "Frågor, kategorier, framsteg",
    "support_topic_technical_title": "Tekniska problem",
    "support_topic_technical_desc": "Appkrascher, synkronisering, notiser",
    "support_faq_title": "Vanliga frågor",
    "support_q1": "Kan jag använda mitt konto på flera enheter?",
    "support_a1": "Ja. Logga in med samma Google- eller Apple-konto på vilken enhet som helst och dina framsteg, prenumerationer och inställningar synkroniseras automatiskt.",
    "support_q2": "Jag kan inte logga in — vad ska jag göra?",
    "support_a2": "Kontrollera att du använder samma inloggningsmetod (Google eller Apple) som du använde vid registreringen. Om problemet kvarstår, prova att logga ut från ditt Google/Apple-konto på enheten och logga in igen. Fortfarande problem? <a href=\"mailto:support@drivetest.se\">Maila oss</a> med din registrerade e-postadress.",
    "support_q3": "Hur raderar jag mitt konto och mina uppgifter?",
    "support_a3": "Du kan begära fullständig radering av konto och data i appen under <strong>Inställningar → Radera konto</strong>, eller besök vår <a href=\"delete-account.html\">sida för kontoborttagning</a> för steg-för-steg-instruktioner.",
    "support_q4": "Hur avslutar jag min prenumeration?",
    "support_q4_a": "Prenumerationer hanteras via App Store (iOS) eller Google Play (Android). På iPhone: gå till <strong>Inställningar → [ditt namn] → Prenumerationer</strong>, välj Drive Test och tryck på <em>Avsluta prenumeration</em>. På Android: öppna Google Play → tryck på din profil → <em>Betalningar och prenumerationer → Prenumerationer</em>.",
    "support_q5": "Jag har blivit debiterad men kan inte komma åt premiuminnehåll.",
    "support_a5": "Gå till <strong>Inställningar → Återställ köp</strong> i appen. Detta validerar om din aktiva prenumeration med App Store eller Google Play. Om problemet kvarstår, <a href=\"mailto:support@drivetest.se\">kontakta oss</a> och inkludera ditt ordernummer eller en skärmdump på kvittot.",
    "support_q6": "Kan jag få en återbetalning?",
    "support_a6": "Återbetalningar hanteras av Apple eller Google. För App Store-köp, besök <a href=\"https://reportaproblem.apple.com\" target=\"_blank\" rel=\"noopener\">reportaproblem.apple.com</a>. För Google Play: öppna Play Store → orderhistorik → tryck på ordern → <em>Begär återbetalning</em>. Vi hjälper gärna till om du har problem.",
    "support_q7": "Jag hittade en felaktig fråga eller ett felaktigt svar.",
    "support_a7": "Vi tar noggrannhet på allvar. Maila oss på <a href=\"mailto:support@drivetest.se\">support@drivetest.se</a> med frågetexten och kategorin där du hittade det. Vi granskar alla rapporter och uppdaterar innehållet regelbundet.",
    "support_q8": "Mitt framsteg har återställts — kan jag återfå det?",
    "support_a8": "Framsteg är knutet till ditt konto och synkroniseras med våra servrar när du är online. Om du nyligen installerat om appen, logga in igen — dina framsteg bör återställas automatiskt inom några sekunder. Saknas data fortfarande? Kontakta oss med din e-post och det ungefärliga datumet för återställningen.",
    "support_q9": "Appen kraschar eller öppnas inte.",
    "support_a9": "Prova dessa steg i ordning: (1) Tvångsstäng appen och öppna den igen. (2) Starta om din enhet. (3) Kontrollera att du kör den senaste versionen från App Store eller Google Play. (4) Installera om appen — dina data är sparade på ditt konto och återställs vid inloggning. Fortfarande problem? <a href=\"mailto:support@drivetest.se\">Hör av dig</a>.",
    "support_q10": "Jag får inga notiser.",
    "support_a10": "Kontrollera att notiser är aktiverade: på iPhone, gå till <strong>Inställningar → Drive Test → Notiser</strong> och se till att de är påslagna. I appen, kontrollera <strong>Inställningar → Notiser</strong> för att säkerställa att dina studiepåminnelser är aktiva. Om du nyligen installerat om appen kan du behöva bevilja notisbehörighet igen.",
    "support_contact_title": "Hur du når oss",
    "support_step1_title": "Kolla vanliga frågor ovan",
    "support_step1_desc": "De flesta frågor besvaras där — det är det snabbaste sättet att få hjälp.",
    "support_step2_title": "Maila oss",
    "support_step2_desc": "Skicka ett meddelande till <strong>support@drivetest.se</strong> och beskriv ditt problem. Inkludera enhetsmodell, iOS/Android-version och appversion om möjligt.",
    "support_step3_title": "Vi återkommer till dig",
    "support_step3_desc": "Vi svarar på alla e-postmeddelanden inom 1–2 arbetsdagar. Komplexa problem kan ta lite längre tid men vi följer alltid upp.",
    "support_cta_title": "Behöver du mer hjälp?",
    "support_cta_desc": "Vårt supportteam är redo att hjälpa dig med alla frågor om Drive Test.",
    "support_cta_email_btn": "✉ Kontakta support",
    "support_cta_delete_btn": "Radera konto",
    "support_badge_reply": "⏱ Svar inom 1–2 arbetsdagar",
    "support_badge_lang": "🌍 Engelska & svenska",
    "page_title_support": "Support - Drive Test",
  },
};
